parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

alias ll="ls -lAh"
alias ls='ls -GFh'
alias con="tail -40 -f /var/log/system.log"

bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

export EDITOR="vi"
export CLICOLOR=1

export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w \$(parse_git_branch) \[\e[00m\]$ "
export LSCOLORS=ExFxBxDxCxegedabagacad

export PATH="$PATH:$HOME/.deliver/bin"
